import os

code_app = '''import streamlit as st
import duckdb
import pandas as pd
import altair as alt
import datetime
import base64
import os
import wren

st.set_page_config(page_title="Executive Overview", layout="wide")
st.title("Executive Operations Overview")
st.markdown("**LIVE SEMANTIC WAREHOUSE** | Governed queries routed through **WrenAI Semantic Layer**.")

col_sync1, col_sync2 = st.columns([3, 1])
with col_sync2:
    if st.button("🔄 Sync Live Data"):
        st.cache_data.clear()
        st.cache_resource.clear()
    st.caption(f"Last Updated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')} UTC")
    st.caption("Engine: WrenAI (DuckDB Connector)")

@st.cache_resource
def get_wren_engine():
    manifest_path = 'wren_project/target/mdl.json'
    if not os.path.exists(manifest_path):
        return None
    with open(manifest_path, 'r', encoding='utf-8') as f:
        manifest_data = f.read()
    manifest_b64 = base64.b64encode(manifest_data.encode('utf-8')).decode('utf-8')
    
    connection_info = {
        "url": "C:\\\\Users\\\\usuario\\\\Documents\\\\GitHub\\\\enterprise-cross-platform-analytics-warehouse\\\\04_clean_data",
        "format": "duckdb"
    }
    
    return wren.WrenEngine(
        manifest_str=manifest_b64,
        data_source="duckdb",
        connection_info=connection_info
    )

engine = get_wren_engine()

@st.cache_data(ttl=300)
def load_kpis_wren():
    if not engine:
        return None, None, None, None, pd.DataFrame(), pd.DataFrame()
        
    # Execute all warehouse queries through the Wren Semantic Layer!
    shop_tbl = engine.query("SELECT COUNT(*), SUM(total_price) FROM fact_shop_orders")
    binance_tbl = engine.query("SELECT last_price FROM fact_binance_klines ORDER BY open_time DESC LIMIT 1")
    prompt_tbl = engine.query("SELECT COUNT(*), AVG(search_interest_score) FROM staging_prompt_telemetry")
    terrazas_tbl = engine.query("SELECT COUNT(*), SUM(total_gross_amount) FROM staging_terrazas_bookings")
    
    shop_df = engine.query("SELECT created_at, total_price FROM fact_shop_orders").to_pandas()
    binance_df = engine.query("SELECT open_time, last_price FROM fact_binance_klines ORDER BY open_time DESC LIMIT 100").to_pandas()
    
    return (
        shop_tbl.to_pandas().values[0],
        binance_tbl.to_pandas().values[0] if len(binance_tbl) > 0 else [0],
        prompt_tbl.to_pandas().values[0],
        terrazas_tbl.to_pandas().values[0],
        shop_df,
        binance_df
    )

try:
    if engine:
        shop, binance, prompt, terrazas, shop_df, binance_df = load_kpis_wren()
        
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("AI Shop Rev (Wren Shop Model)", f"${shop[1]:,.2f}")
        c2.metric("BTC (Wren Binance Model)", f"${binance[0]:,.2f}", 'Semantic')
        c3.metric("Prompt Reqs (Wren Prompt Model)", f"{prompt[0]} reqs")
        c4.metric("Terrazas Rev (Wren Terrazas Model)", f"${terrazas[1]:,.2f}")
        
        st.write("---")
        st.subheader("High-Level Global Metrics (Wren Governed Datasets)")
        col_a, col_b = st.columns(2)
        
        with col_a:
            if not shop_df.empty:
                c = alt.Chart(shop_df).mark_line(color='green').encode(x='created_at', y='total_price').properties(height=200, title="Shopify Revenue Timeline")
                st.altair_chart(c, use_container_width=True)
                
        with col_b:
            if not binance_df.empty:
                c = alt.Chart(binance_df).mark_area(opacity=0.5, color='orange').encode(x='open_time', y=alt.Y('last_price', scale=alt.Scale(zero=False))).properties(height=200, title="BTC Price Action")
                st.altair_chart(c, use_container_width=True)
                
        st.write("---")
        st.subheader("Interactive WrenAI Semantic Playground")
        st.markdown("""
        WrenAI uses a **Modeling Definition Language (MDL)** semantic mapping. 
        When you submit a query, Wren translates, qualifies, and dry-plans it before execution.
        """)
        
        predefined_queries = {
            "Total Shopify Sales by Device Type": "SELECT device_type, sum(total_price) as sales FROM fact_shop_orders GROUP BY device_type",
            "Latest HackerNews Story Count": "SELECT count(*) FROM ext_hackernews_tech",
            "Open-Meteo Weather Forecast (Juarez)": "SELECT forecast_date, max_temp FROM ext_juarez_weather",
            "Top Github Repos (Stargazers)": "SELECT name, stargazers_count FROM ext_github_agent_demand ORDER BY stargazers_count DESC LIMIT 5"
        }
        
        selected_q = st.selectbox("Select a query to execute through WrenAI:", list(predefined_queries.keys()))
        sql_query = predefined_queries[selected_q]
        
        # Show AST dry-plan generated by WrenEngine
        st.write("**WrenAI Compiled AST Query plan (Dry Plan):**")
        dry_plan_sql = engine.dry_plan(sql_query)
        st.code(dry_plan_sql, language='sql')
        
        # Execute query
        st.write("**Query Execution Result:**")
        res_df = engine.query(sql_query).to_pandas()
        st.dataframe(res_df, use_container_width=True)
        
        # Render a small dynamically selected chart based on query results
        if len(res_df.columns) >= 2 and len(res_df) > 0:
            c_type = res_df.columns[0]
            c_val = res_df.columns[1]
            if res_df[c_val].dtype in ['float64', 'int64']:
                chart = alt.Chart(res_df).mark_bar(color='purple').encode(x=c_type, y=c_val).properties(height=180, title=f"Visualized: {selected_q}")
                st.altair_chart(chart, use_container_width=True)

    else:
        st.error("WrenAI Engine could not be loaded. Manifest target/mdl.json is missing.")
except Exception as e:
    st.error(f"Error loading WrenAI engine data: {e}")
'''

with open('05_dashboard/app.py', 'w', encoding='utf-8') as f:
    f.write(code_app)

print("Successfully integrated WrenEngine semantic layer and playground into Streamlit app.py!")
